spring:
  data:
    mongodb:
      uri: uri
redis:
  host: host
  port: port
ibkr:
  urls:
    generateReport: https://ndcdyn.interactivebrokers.com/AccountManagement/FlexWebService/SendRequest
    getReport: https://ndcdyn.interactivebrokers.com/AccountManagement/FlexWebService/GetStatement

jwt:
  secret: secret
  expiration: 3600000

encryption:
  secret: secret

internal:
  secret: super-secret-123