spring:
  profiles:
    active: local
  data:
    mongodb:
      uri: ""
    redis:
      host: local
      port: 6397
ibkr:
  urls:
    generateReport: https://ndcdyn.interactivebrokers.com/AccountManagement/FlexWebService/SendRequest
    getReport: https://ndcdyn.interactivebrokers.com/AccountManagement/FlexWebService/GetStatement
  secrets:
    flexToken: flexToken
    flexQueryId: flexQueryId

jwt:
  secret: secret
  expiration: 3600000

crypto:
  secret: secret
